# Generated by Django 3.2.8 on 2023-02-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_Category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDataImage',
            fields=[
                ('College_Image_Id', models.AutoField(primary_key=True, serialize=False)),
                ('College_Image', models.FileField(max_length=1000, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('collegeType', models.CharField(max_length=254)),
                ('coursesOffered', models.CharField(max_length=254)),
                ('campusType', models.CharField(max_length=254)),
                ('examDate', models.DateField(default='2023-02-22')),
                ('address', models.CharField(max_length=254)),
                ('websiteLink', models.CharField(max_length=254)),
                ('contactNumber', models.CharField(max_length=254)),
                ('alteratePhoneNumber', models.CharField(max_length=254)),
                ('votes', models.IntegerField()),
                ('linkName', models.CharField(blank=True, max_length=254, null=True)),
                ('link', models.CharField(blank=True, max_length=254, null=True)),
                ('linkButtonName', models.CharField(blank=True, max_length=254, null=True)),
                ('youtubeUrls', models.JSONField(blank=True, default=list, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(related_name='college_category', to='CollegeDetail.CollegeCategory')),
                ('collegeImages', models.ManyToManyField(related_name='college_images', to='CollegeDetail.CollegeDataImage')),
            ],
        ),
    ]
