# Generated by Django 3.2.8 on 2023-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecategory',
            name='College_Category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='collegedetailmodel',
            name='examDate',
            field=models.DateField(default='2023-02-27'),
        ),
    ]
